[build]
  publish = "build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/api/*"
  to = "https://portfolio-backend-593g.onrender.com/api/:splat"
  status = 200

# Redirection pour les routes admin (SPA)
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

# Redirection pour toutes les autres routes SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
