import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Traductions
const translations = {
  fr: {
    // Navigation
    home: "Accueil",
    about: "À propos",
    skills: "Compétences",
    projects: "Projets",
    services: "Services",
    contact: "Contact",
    blog: "Blog",
    calculator: "Calculateur", 
    booking: "Réservation",
    tools: "Outils",
    resources: "Ressources",
    
    // Hero Section
    specialist: "Spécialiste",
    cybersecurity: "Cybersécurité",
    developer: "Développeur",
    subtitle: "Expert en sécurité numérique et développement d'applications Python",
    heroDescription: "Expert en sécurité numérique et développement d'applications Python. J'accompagne les entreprises dans leur transformation digitale sécurisée.",
    discoverProjects: "Découvrir mes projets",
    myServices: "Mes services",
    
    // Stats
    projectsCompleted: "Projets réalisés",
    clientsSatisfied: "Clients satisfaits",
    vulnerabilitiesDetected: "Vulnérabilités détectées",
    developmentHours: "Heures de développement",
    
    // Common
    loading: "Chargement...",
    readMore: "Lire plus",
    viewAll: "Voir tout",
    seeMore: "Voir plus",
    requestQuote: "Demander un devis",
    contactMe: "Contactez-moi",
    learnMore: "En savoir plus",
    getStarted: "Commencer",
    download: "Télécharger",
    preview: "Aperçu",
    
    // About
    myJourney: "Mon parcours",
    myMission: "Ma mission",
    workProcess: "Mon processus de travail",
    personalizedApproach: "Approche personnalisée",
    technicalExpertise: "Expertise technique",
    concreteResults: "Résultats concrets",
    reactivity: "Réactivité",
    
    // Skills
    mySkills: "Mes compétences",
    technicalExpertiseSubtitle: "Expertise technique en cybersécurité, développement Python et infrastructure réseau",
    technologiesTools: "Technologies & Outils",
    continuousTraining: "Formation continue",
    skillsNotConfigured: "Compétences non configurées",
    noSkillsMessage: "Les compétences pour cette catégorie n'ont pas encore été ajoutées.",
    skillsNotAvailable: "Compétences non disponibles",
    skillsContactAdmin: "Les données de compétences ne sont pas encore configurées. Veuillez contacter l'administrateur.",
    technologiesNotConfigured: "Technologies non configurées",
    technologiesNotConfiguredMessage: "Les technologies et outils ne sont pas encore configurés.",
    strengthsTitle: "Points forts",
    proactiveSecurity: "Sécurité Proactive",
    proactiveSecurityDesc: "Approche préventive de la sécurité avec mise en place de systèmes de détection et de protection contre les menaces émergentes.",
    secureCode: "Code Sécurisé",
    secureCodeDesc: "Développement d'applications Python avec les meilleures pratiques de sécurité et respect des standards industriels.",
    technicalExcellence: "Excellence Technique",
    technicalExcellenceDesc: "Engagement vers l'excellence avec une formation continue et une veille technologique constante dans le domaine de la cybersécurité.",
    skillsInterest: "Mes compétences vous intéressent ?",
    skillsInterestDesc: "Découvrez comment je peux mettre mon expertise au service de vos projets en cybersécurité et développement Python.",
    viewMyProjects: "Voir mes projets",
    dailyTechWatch: "Veille technologique quotidienne",
    ctfParticipation: "Participation à des CTF (Capture The Flag)",
    onlineTraining: "Formations en ligne spécialisées",
    openSourceContrib: "Contribution à des projets open source",
    
    // Projects
    myProjects: "Mes projets",
    projectsSubtitle: "Découvrez mes réalisations techniques en cybersécurité, Python et développement",
    filterByCategory: "Filtrer par catégorie",
    filterByLevel: "Filtrer par niveau",
    allProjects: "Tous les projets",
    allLevels: "Tous niveaux",
    beginner: "Débutant",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    completed: "Terminé",
    inProgress: "En cours",
    planned: "Planifié",
    keyFeatures: "Fonctionnalités clés",
    duration: "Durée",
    
    // Services
    myServicesTitle: "Mes services",
    servicesSubtitle: "Solutions professionnelles en cybersécurité, développement Python et infrastructure",
    collaborationProcess: "Mon processus de collaboration",
    whatClientsSay: "Ce que disent mes clients",
    frequentlyAsked: "Questions fréquentes",
    
    // Contact
    contactTitle: "Contactez-moi",
    contactSubtitle: "Discutons de vos besoins en cybersécurité et développement Python",
    contactInfo: "Informations de contact",
    socialNetworks: "Réseaux sociaux",
    quickResponse: "Réponse rapide",
    sendMessage: "Envoyez-moi un message",
    fullName: "Nom complet",
    email: "Email",
    subject: "Sujet",
    message: "Message",
    serviceOfInterest: "Service d'intérêt",
    selectService: "Sélectionnez un service",
    sendingMessage: "Envoi en cours...",
    sendMessageBtn: "Envoyer le message",
    
    // Testimonials
    testimonials: "Témoignages",
    shareExperience: "Partagez votre expérience",
    helpOthers: "Aidez d'autres clients en partageant votre témoignage",
    testimonialFormTitle: "Partagez votre expérience",
    testimonialFormDesc: "Votre témoignage nous aide à améliorer nos services et inspire d'autres clients",
    company: "Entreprise",
    role: "Fonction",
    serviceUsed: "Service utilisé",
    rating: "Évaluation",
    ratingHelper: "Cliquez sur les étoiles pour noter notre service",
    yourTestimonial: "Votre témoignage",
    testimonialPlaceholder: "Partagez votre expérience avec nos services...",
    testimonialNote: "Votre témoignage sera examiné avant publication. Nous nous réservons le droit de modifier ou refuser la publication de témoignages inappropriés.",
    testimonialConsent: "En soumettant ce formulaire, vous acceptez que votre témoignage puisse être publié sur notre site web.",
    sendTestimonial: "Envoyer mon témoignage",
    sendingTestimonial: "Envoi en cours...",
    
    // Blog
    technicalBlog: "Blog Technique",
    blogSubtitle: "Articles et tutoriels sur la cybersécurité et le développement Python",
    readingTime: "min de lecture",
    publishedOn: "Publié le",
    category: "Catégorie",
    tags: "Tags",
    
    // Resources
    resourcesTitle: "Centre de ressources",
    resourcesSubtitle: "Guides, outils et ressources gratuits pour la cybersécurité",
    downloadResource: "Télécharger",
    downloads: "téléchargements",
    featured: "À la une",
    freeResources: "Ressources gratuites",
    
    // About Page
    aboutMe: "À propos de moi",
    aboutMeSubtitle: "Découvrez mon parcours et ma passion pour la cybersécurité",
    myJourney: "Mon parcours",
    myMission: "Ma mission",
    workProcess: "Mon processus de travail",
    personalizedApproach: "Approche personnalisée",
    technicalExpertise: "Expertise technique",
    concreteResults: "Résultats concrets",
    reactivity: "Réactivité",
    personalizedApproachDesc: "Chaque projet est unique, j'adapte mes solutions à vos besoins spécifiques.",
    technicalExpertiseDesc: "Formation continue aux dernières technologies et menaces émergentes.",
    concreteResultsDesc: "Focus sur l'efficacité et la sécurité mesurable de vos systèmes.",
    reactivityDesc: "Disponibilité et réponse rapide pour vos urgences sécuritaires.",
    constantTechWatch: "Veille technologique constante",
    ethicalResponsibleApproach: "Approche éthique et responsable",
    pedagogyTransmission: "Pédagogie et transmission",
    myMissionDesc: "Démocratiser la cybersécurité et rendre les technologies sûres et accessibles à tous. Mon objectif est d'accompagner les entreprises dans leur transformation digitale sécurisée, en mettant l'accent sur la prévention et l'éducation.",
    someNumbers: "Quelques chiffres",
    readyToCollaborate: "Prêt à collaborer ?",
    readyToCollaborateDesc: "Je suis toujours ouvert aux nouveaux défis et collaborations. Parlons de vos besoins en cybersécurité et développement Python.",
    viewMyProjects: "Voir mes projets",
    
    // Contact Page
    contactMe: "Contactez-moi",
    contactSubtitle: "Discutons de vos besoins en cybersécurité et développement Python",
    contactInfo: "Informations de contact",
    socialNetworks: "Réseaux sociaux",
    quickResponse: "Réponse rapide",
    sendMessage: "Envoyez-moi un message",
    fullName: "Nom complet",
    email: "Email",
    subject: "Sujet",
    message: "Message",
    serviceOfInterest: "Service d'intérêt",
    selectService: "Sélectionnez un service",
    securityAudit: "Audit de sécurité",
    pythonDevelopment: "Développement Python",
    infrastructureSecurity: "Sécurisation d'infrastructure",
    consultingTraining: "Consulting & Formation",
    other: "Autre",
    phone: "Téléphone",
    location: "Localisation",
    availability: "Disponibilité",
    responseWithin24h: "Réponse sous 24h maximum",
    freeQuoteNoCommitment: "Devis gratuit et sans engagement",
    freeInitialConsultation: "Consultation initiale offerte",
    technicalSupportIncluded: "Support technique inclus",
    sendingMessage: "Envoi en cours...",
    sendMessageBtn: "Envoyer le message",
    messageSentSuccess: "Message envoyé avec succès ! Je vous répondrai rapidement.",
    shareExperience: "Partagez votre expérience",
    helpOthers: "Aidez d'autres clients en partageant votre témoignage",
    yourName: "Votre nom",
    yourEmail: "votre@email.com",
    subjectOfMessage: "Sujet de votre message",
    describeProject: "Décrivez votre projet ou vos besoins...",
    
    // Footer
    followMe: "Suivez-moi",
    backToTop: "Retour en haut",
    allRightsReserved: "Tous droits réservés",
    createdWith: "Créé avec",
    andCoffee: "et beaucoup de café",
    navigation: "Navigation",
    services: "Services",
    secureInfrastructure: "Infrastructure sécurisée",
    
    // Error States
    dataNotAvailable: "Données non disponibles",
    contactAdministrator: "Veuillez contacter l'administrateur",
    tryAgainLater: "Veuillez réessayer plus tard",
    
    // Home page sections
    freeTools: "Outils gratuits",
    freeToolsDesc: "Utilisez gratuitement nos outils en ligne pour vos besoins en cybersécurité",
    priceCalculator: "Calculateur de Prix",
    priceCalculatorDesc: "Obtenez une estimation instantanée pour votre projet de cybersécurité",
    calculateNow: "Calculer maintenant",
    freeResourcesHome: "Ressources Gratuites",
    freeResourcesHomeDesc: "Téléchargez gratuitement nos guides, scripts et templates",
    downloadNow: "Télécharger",
    technicalBlogHome: "Blog Technique",
    technicalBlogHomeDesc: "Découvrez mes articles sur la cybersécurité et Python",
    readArticles: "Lire les articles",
    skillsOverview: "Aperçu de mes compétences",
    skillsOverviewDesc: "Un aperçu de mes domaines d'expertise en cybersécurité et développement",
    featuredProjects: "Projets en vedette",
    featuredProjectsDesc: "Découvrez quelques-uns de mes projets les plus remarquables",
    viewAllProjects: "Voir tous les projets",
    whatClientsSay: "Ce que disent mes clients",
    
    // Footer
    footerDescription: "Spécialiste en cybersécurité et développement Python. J'accompagne les entreprises dans leur transformation digitale sécurisée avec une approche moderne et efficace.",
    skillsTags: ["Cybersécurité", "Python", "Sécurité Réseau", "Développement Web", "IoT", "Cloud Computing", "DevOps", "Pentesting"],
    
    // Dynamic data translations (Skills, Technologies, etc)
    translations: {
      // Skill categories
      'Cybersécurité': 'Cybersécurité',
      'Python': 'Python',
      'Réseaux': 'Réseaux',
      'Développement Python': 'Développement Python',
      'Réseau & Infrastructure': 'Réseau & Infrastructure',
      
      // Skills
      'Tests de pénétration': 'Tests de pénétration',
      'Audit de sécurité': 'Audit de sécurité',
      'Sécurisation réseau': 'Sécurisation réseau',
      'Développement Python': 'Développement Python',
      'Automatisation': 'Automatisation',
      'Analyse de données': 'Analyse de données',
      'Configuration réseau': 'Configuration réseau',
      'Monitoring': 'Monitoring',
      'Troubleshooting': 'Troubleshooting',
      'Pentesting': 'Pentesting',
      'Forensique': 'Forensique',
      'Conformité RGPD': 'Conformité RGPD',
      'Sécurité des réseaux': 'Sécurité des réseaux',
      'Django/FastAPI': 'Django/FastAPI',
      'APIs REST': 'APIs REST',
      'Tests unitaires': 'Tests unitaires',
      'Data Science': 'Data Science',
      'Administration Linux': 'Administration Linux',
      'Firewalls': 'Firewalls',
      'Virtualisation': 'Virtualisation',
      'Security Audit': 'Audit de sécurité',
      'Penetration Testing': 'Tests de pénétration',
      'Vulnerability Analysis': 'Analyse de vulnérabilités',
      
      // Project categories and levels
      'Débutant': 'Débutant',
      'Intermédiaire': 'Intermédiaire',
      'Avancé': 'Avancé',
      'Terminé': 'Terminé',
      'En cours': 'En cours',
      'Planifié': 'Planifié',
      
      // Service types
      'Audit de sécurité': 'Audit de sécurité',
      'Tests de pénétration': 'Tests de pénétration',
      'Consultation cybersécurité': 'Consultation cybersécurité',
      'Développement d\'applications': 'Développement d\'applications',
      'Scripts d\'automatisation': 'Scripts d\'automatisation',
      'Formation': 'Formation',
      
      // Blog categories
      'Tutoriel': 'Tutoriel',
      'Actualités': 'Actualités',
      'Outils': 'Outils',
      'Conseils': 'Conseils',
      
      // Statistics
      'Projets réalisés': 'Projets réalisés',
      'Clients satisfaits': 'Clients satisfaits',
      'Vulnérabilités détectées': 'Vulnérabilités détectées',
      'Heures de développement': 'Heures de développement',
      'Années d\'expérience': 'Années d\'expérience',
      'Certifications': 'Certifications',
      'Projets Totaux': 'Projets Totaux',
      'Taux d\'Achèvement': 'Taux d\'Achèvement',
      'Articles Publiés': 'Articles Publiés',
      'Technologies': 'Technologies',
      'Témoignages': 'Témoignages',
      'En Attente': 'En Attente',
      'Note Moyenne': 'Note Moyenne',
      'Téléchargements': 'Téléchargements',
      'Compétences': 'Compétences',
      'Niveau Expert': 'Niveau Expert',
      'Services': 'Services',
      'Réservations': 'Réservations',
      'Devis Demandés': 'Devis Demandés',
      'Abonnés Newsletter': 'Abonnés Newsletter',
      'Activité (30j)': 'Activité (30j)',
      'Projets Sécurisés': 'Projets Sécurisés',
      'Satisfaction Client': 'Satisfaction Client',
      
      // Services - Titles
      'Audit de Sécurité': 'Audit de Sécurité',
      'Développement Python': 'Développement Python',
      'Sécurisation d\'Infrastructure': 'Sécurisation d\'Infrastructure',
      'Consulting & Formation': 'Consulting & Formation',
      
      // Services - Features/Descriptions
      'Analyse complète de votre infrastructure pour identifier les vulnérabilités et risques potentiels.': 'Analyse complète de votre infrastructure pour identifier les vulnérabilités et risques potentiels.',
      'Développement d\'applications Python sécurisées et performantes selon vos besoins.': 'Développement d\'applications Python sécurisées et performantes selon vos besoins.',
      'Mise en place et configuration de solutions de sécurité pour votre infrastructure IT.': 'Mise en place et configuration de solutions de sécurité pour votre infrastructure IT.',
      'Conseil stratégique et formation de vos équipes en cybersécurité.': 'Conseil stratégique et formation de vos équipes en cybersécurité.',
      
      // Services - Features
      'Audit technique complet': 'Audit technique complet',
      'Test de pénétration': 'Test de pénétration',
      'Analyse des vulnérabilités': 'Analyse des vulnérabilités',
      'Rapport détaillé': 'Rapport détaillé',
      'Recommandations d\'amélioration': 'Recommandations d\'amélioration',
      'Architecture sécurisée': 'Architecture sécurisée',
      'APIs REST performantes': 'APIs REST performantes',
      'Tests unitaires et intégration': 'Tests unitaires et intégration',
      'Documentation technique': 'Documentation technique',
      'Support et maintenance': 'Support et maintenance',
      'Configuration des firewalls': 'Configuration des firewalls',
      'Monitoring et alertes': 'Monitoring et alertes',
      'Sauvegarde et récupération': 'Sauvegarde et récupération',
      'Politiques de sécurité': 'Politiques de sécurité',
      'Formation du personnel': 'Formation du personnel',
      'Évaluation des risques': 'Évaluation des risques',
      'Plan de réponse aux incidents': 'Plan de réponse aux incidents',
      'Certification et conformité': 'Certification et conformité',
      
      // Skills - Individual Skills
      'Audit de sécurité': 'Audit de sécurité',
      'Tests de pénétration': 'Tests de pénétration',
      'Analyse de vulnérabilités': 'Analyse de vulnérabilités',
      'Sécurité réseau': 'Sécurité réseau',
      'Forensic numérique': 'Forensique numérique',
      'Conformité GDPR': 'Conformité GDPR',
      'Scripts d\'automatisation': 'Scripts d\'automatisation',
      'APIs REST': 'APIs REST',
      'Analyse de données': 'Analyse de données',
      'Machine Learning': 'Machine Learning',
      'Configuration réseau': 'Configuration réseau',
      'Administration système': 'Administration système',
      'Virtualisation': 'Virtualisation',
      'Cloud computing': 'Cloud computing',
      
      // Projects - Categories and Types
      'Scanner de Sécurité': 'Scanner de Sécurité',
      'Analyse Forensique': 'Analyse Forensique',
      'Automatisation': 'Automatisation',
      'Infrastructure': 'Infrastructure',
      'Application Web': 'Application Web',
      'Script Python': 'Script Python',
      'Outil de Monitoring': 'Outil de Monitoring',
      
      // Projects - Specific project names and descriptions would need to be added based on actual data
      'Vérificateur d\'Intégrité de Fichiers': 'Vérificateur d\'Intégrité de Fichiers',
      'Analyseur de Logs de Sécurité': 'Analyseur de Logs de Sécurité',
      'Scanner de Vulnérabilités Web': 'Scanner de Vulnérabilités Web',
      
      // Project descriptions
      'Outil Python pour surveiller l\'intégrité des fichiers système et détecter les modifications non autorisées.': 'Outil Python pour surveiller l\'intégrité des fichiers système et détecter les modifications non autorisées.',
      'Script avancé pour analyser les logs de sécurité et identifier les tentatives d\'intrusion.': 'Script avancé pour analyser les logs de sécurité et identifier les tentatives d\'intrusion.',
      'Application web pour scanner et identifier les vulnérabilités communes dans les applications web.': 'Application web pour scanner et identifier les vulnérabilités communes dans les applications web.',
      
      // Project features
      'Calcul de hash MD5/SHA256': 'Calcul de hash MD5/SHA256',
      'Surveillance des changements': 'Surveillance des changements',
      'Base de données d\'empreintes': 'Base de données d\'empreintes',
      'Notifications en cas de modification': 'Notifications en cas de modification',
      'Interface en ligne de commande': 'Interface en ligne de commande',
      'Détection d\'anomalies': 'Détection d\'anomalies',
      'Parsing de logs Apache/Nginx': 'Parsing de logs Apache/Nginx',
      'Alertes en temps réel': 'Alertes en temps réel',
      'Rapports automatisés': 'Rapports automatisés',
      'Dashboard de visualisation': 'Dashboard de visualisation',
      'Tests OWASP Top 10': 'Tests OWASP Top 10',
      'Interface web moderne': 'Interface web moderne',
      'Gestion des utilisateurs': 'Gestion des utilisateurs',
      'Export des résultats': 'Export des résultats',
      'Scan automatisé': 'Scan automatisé',
      
      // Process Steps
      'Contact initial': 'Contact initial',
      'Analyse des besoins': 'Analyse des besoins',
      'Proposition technique': 'Proposition technique',
      'Développement': 'Développement',
      'Livraison': 'Livraison',
      
      // Process Steps descriptions
      'Étude détaillée de votre problématique et définition des objectifs.': 'Étude détaillée de votre problématique et définition des objectifs.',
      'Première prise de contact pour comprendre vos besoins.': 'Première prise de contact pour comprendre vos besoins.',
      'Présentation d\'une solution technique adaptée à vos besoins.': 'Présentation d\'une solution technique adaptée à vos besoins.',
      'Réalisation de la solution avec des points de contrôle réguliers.': 'Réalisation de la solution avec des points de contrôle réguliers.',
      'Déploiement, formation et suivi de la solution mise en place.': 'Déploiement, formation et suivi de la solution mise en place.',
      
      // Technologies
      'JavaScript': 'JavaScript',
      'React': 'React',
      'Node.js': 'Node.js',
      'PostgreSQL': 'PostgreSQL',
      'MongoDB': 'MongoDB',
      'Docker': 'Docker',
      'Kubernetes': 'Kubernetes',
      'AWS': 'AWS',
      'Azure': 'Azure',
      'Linux': 'Linux',
      'Windows': 'Windows',
      'Nmap': 'Nmap',
      'Wireshark': 'Wireshark',
      'Metasploit': 'Metasploit',
      'Burp Suite': 'Burp Suite',
      'Git': 'Git',
      'Jenkins': 'Jenkins',
      'Ansible': 'Ansible',
      'Terraform': 'Terraform',
      
      // Additional dynamic translations
      'Forensique': 'Forensique',
      'Planifié': 'Planifié'
    },

    // Interactive Tools Page Translations
    interactiveTools: "Outils Interactifs",
    interactiveToolsTitle: "Outils de Cybersécurité",
    interactiveToolsSubtitle: "Collection d'outils en ligne pour vos besoins en cybersécurité",
    interactiveToolsDesc: "Explorez notre gamme d'outils professionnels de cybersécurité. Analysez, testez et sécurisez vos systèmes avec nos utilitaires spécialisés développés par des experts.",
    freeOnlineTools: "Outils gratuits en ligne",
    chooseToolBelow: "Choisissez un outil ci-dessous pour commencer votre analyse",
    
    // Tool Interface Labels
    analysisResults: "Résultats de l'analyse",
    securityScore: "Score de sécurité",
    suggestedImprovements: "Améliorations suggérées",
    analysisResult: "Résultat de l'analyse",
    scanResults: "Résultats du scan",
    validationResults: "Résultat de validation",
    xssAnalysisResults: "Résultats de l'analyse XSS",
    
    // Common Tool Actions
    enterText: "Entrez le texte",
    enterPassword: "Entrez le mot de passe",
    enterUrl: "Entrez l'URL",
    enterHost: "Entrez l'hôte",
    enterJson: "Entrez le JSON",
    enterCode: "Entrez le code",
    
    // Tool Specific Labels - Password Analyzer
    passwordAnalyzerTitle: "Analyseur de Mots de Passe",
    passwordToAnalyze: "Mot de passe à analyser",
    passwordPlaceholder: "Entrez un mot de passe...",
    excellentPassword: "Excellent mot de passe!",
    entropy: "Entropie",
    
    // Tool Specific Labels - Port Scanner
    portScannerTitle: "Scanner de Ports",
    portScannerSimulation: "Scanner de Ports (Simulation)",
    targetHostLabel: "Adresse IP ou nom d'hôte cible",
    targetHostPlaceholder: "192.168.1.1 ou example.com",
    startScan: "Démarrer le scan",
    scanInProgress: "Scan en cours",
    portsScanned: "ports testés",
    educationalSimulation: "⚠️ Ceci est une simulation éducative. En pratique, ne scannez que vos propres systèmes ou avec autorisation.",
    
    // Tool Specific Labels - Cipher Tool
    cipherToolTitle: "Chiffreur/Déchiffreur",
    cipherToolAES: "Chiffreur/Déchiffreur AES",
    textToCipher: "Texte à chiffrer",
    cipherText: "Texte chiffré",
    encryptionKey: "Clé de chiffrement",
    secretKey: "Clé secrète...",
    enterMessage: "Entrez votre message...",
    enterCipherText: "Entrez le texte chiffré...",
    result: "Résultat",
    
    // Tool Specific Labels - URL Analyzer  
    urlAnalyzerTitle: "Analyseur d'URL",
    urlToAnalyze: "URL à analyser",
    urlPlaceholder: "https://example.com/path?param=value",
    urlAnalysisTitle: "Analyse de l'URL",
    protocol: "Protocole",
    hostname: "Nom d'hôte",
    port: "Port",
    path: "Chemin",
    queryParams: "Paramètres de requête",
    pathSegments: "Segments du chemin",
    origin: "Origine",
    secured: "✓ Sécurisé",
    
    // Tool Specific Labels - XSS Detector
    xssDetectorTitle: "Détecteur XSS",
    xssAnalysisReport: "Rapport d'analyse XSS",
    codeToAnalyze: "Code HTML/JavaScript à analyser",
    xssCodePlaceholder: "Collez votre code HTML ou JavaScript ici...",
    analyzeXssThreats: "Analyser les menaces XSS",
    highRisk: "RISQUE ÉLEVÉ",
    mediumRisk: "RISQUE MOYEN", 
    secured: "SÉCURISÉ",
    threatsDetected: "Menaces détectées",
    vulnerabilities: "vulnérabilités",
    detectedVulnerabilities: "Vulnérabilités détectées",
    recommendations: "Recommandations",
    position: "Position",
    xssEducationalNote: "ℹ️ Cet outil détecte les patterns XSS potentiels dans le code HTML/JavaScript à des fins éducatives.",
    
    // Tool Specific Labels - JSON Validator
    jsonValidatorTitle: "Validateur JSON",
    jsonToValidate: "JSON à valider et formater",
    jsonPlaceholder: '{"exemple": "Collez votre JSON ici...", "tableau": [1, 2, 3]}',
    validateJson: "Valider JSON",
    copyFormattedJson: "Copier JSON formaté",
    jsonValid: "JSON VALIDE",
    jsonInvalid: "JSON INVALIDE",
    jsonStructureAnalysis: "Analyse de la structure",
    // Password feedback messages
    atLeast8Chars: "Au moins 8 caractères",
    lowercaseLetters: "Lettres minuscules", 
    uppercaseLetters: "Lettres majuscules",
    numbers: "Chiffres",
    specialChars: "Caractères spéciaux",
    avoidRepetitions: "Éviter les répétitions",
    excellentPassword: "Excellent mot de passe!",
    
    // Password strength levels
    passwordStrengthWeak: "Faible",
    passwordStrengthMedium: "Moyen",
    passwordStrengthStrong: "Fort", 
    passwordStrengthVeryStrong: "Très Fort",
    
    // Cipher error messages
    errorIncorrectKey: "Erreur: Clé incorrecte ou texte invalide",
    errorCipherOperation: "Erreur lors du chiffrement/déchiffrement",
    
    // URL analysis error
    invalidUrl: "URL invalide",
    
    // XSS security recommendations
    escapeScriptTags: "Échappez ou supprimez les balises <script>",
    removeEventHandlers: "Supprimez les gestionnaires d'événements inline (onclick, onload, etc.)",
    avoidJsUrls: "Évitez les URLs javascript:",
    validateIframeSources: "Validez les sources des iframes",
    useHtmlEscaping: "Utilisez toujours l'échappement HTML approprié",
    implementCSP: "Implémentez une Content Security Policy (CSP)",
    contentSafe: "Le contenu semble sûr, mais restez vigilant",
    
    // JSON error suggestions
    checkMissingCommas: "Vérifiez les virgules manquantes ou en trop",
    useDoubleQuotes: "Assurez-vous que les chaînes sont entre guillemets doubles",
    checkMissingBrackets: "Vérifiez les accolades ou crochets manquants", 
    stringsNeedQuotes: "Les chaînes doivent être entre guillemets doubles (\")",
    useOnlineValidator: "Utilisez un validateur JSON en ligne pour identifier l'erreur",
    
    // Tool Names
    hashGenerator: "Générateur de Hash",
    passwordAnalyzer: "Analyseur de Mots de Passe",
    portScanner: "Scanner de Ports",
    cipherTool: "Chiffreur/Déchiffreur",
    urlAnalyzer: "Analyseur d'URL",
    xssDetector: "Détecteur XSS",
    jsonValidator: "Validateur JSON",
    
    // Tool Descriptions
    hashGeneratorDesc: "Générez des hashes MD5, SHA1, SHA256",
    passwordAnalyzerDesc: "Vérifiez la force des mots de passe",
    portScannerDesc: "Simulation de scan de ports",
    cipherToolDesc: "Chiffrement/déchiffrement AES",
    urlAnalyzerDesc: "Analysez la structure des URLs",
    xssDetectorDesc: "Détectez les vulnérabilités XSS potentielles",
    jsonValidatorDesc: "Validez et formatez du JSON",
    
    // Results History
    resultsHistory: "Historique des résultats",
    showHistory: "Afficher l'historique",
    hideHistory: "Masquer l'historique",
    savedResults: "résultats sauvegardés",
    noSavedResults: "Aucun résultat sauvegardé",
    exportResults: "Exporter les résultats",
    clearAllResults: "Effacer tous les résultats",
    deleteResult: "Supprimer ce résultat",
    
    // Common Tool Actions
    generate: "Générer",
    analyze: "Analyser",
    scan: "Scanner",
    encrypt: "Chiffrer",
    decrypt: "Déchiffrer",
    validate: "Valider",
    detect: "Détecter",
    copy: "Copier",
    copied: "Copié!",
    save: "Sauvegarder",
    saved: "Sauvegardé!",
    clear: "Effacer",
    reset: "Réinitialiser",
    
    // Hash Generator
    hashGeneratorTitle: "Générateur de Hash",
    enterTextToHash: "Texte à hasher",
    enterTextPlaceholder: "Entrez le texte à hasher...",
    generateHashes: "Générer les hashes",
    hashResults: "Résultats des hashes",
    copyHash: "Copier le hash",
    saveHashResults: "Sauvegarder les résultats",
    
    // Password Analyzer
    passwordAnalyzerTitle: "Analyseur de Mots de Passe",
    enterPassword: "Mot de passe à analyser",
    passwordPlaceholder: "Entrez le mot de passe à analyser...",
    passwordStrength: "Force du mot de passe",
    securityScore: "Score de sécurité",
    entropy: "Entropie",
    recommendations: "Recommandations",
    passwordStrengthWeak: "Faible",
    passwordStrengthMedium: "Moyen",
    passwordStrengthStrong: "Fort",
    passwordStrengthVeryStrong: "Très Fort",
    atLeast8Chars: "Au moins 8 caractères",
    lowercaseLetters: "Lettres minuscules",
    uppercaseLetters: "Lettres majuscules",
    numbers: "Chiffres",
    specialChars: "Caractères spéciaux",
    avoidRepetitions: "Éviter les répétitions",
    savePasswordResults: "Sauvegarder l'analyse",
    
    // Port Scanner
    portScannerTitle: "Scanner de Ports",
    targetHost: "Hôte cible",
    targetHostPlaceholder: "Entrez l'adresse IP ou le nom d'hôte...",
    startScan: "Démarrer le scan",
    scanInProgress: "Scan en cours",
    scanResults: "Résultats du scan",
    port: "Port",
    status: "Statut",
    service: "Service",
    openPorts: "Ports ouverts",
    closedPorts: "Ports fermés",
    saveScanResults: "Sauvegarder le scan",
    
    // Cipher Tool
    cipherToolTitle: "Chiffreur/Déchiffreur",
    textToCipher: "Texte à chiffrer/déchiffrer",
    cipherTextPlaceholder: "Entrez le texte à chiffrer ou déchiffrer...",
    encryptionKey: "Clé de chiffrement",
    keyPlaceholder: "Entrez la clé de chiffrement...",
    mode: "Mode",
    encryptMode: "Chiffrer",
    decryptMode: "Déchiffrer",
    performOperation: "Effectuer l'opération",
    cipherResult: "Résultat",
    errorIncorrectKey: "Erreur: Clé incorrecte ou texte invalide",
    errorCipherOperation: "Erreur lors du chiffrement/déchiffrement",
    saveCipherResults: "Sauvegarder le résultat",
    
    // URL Analyzer
    urlAnalyzerTitle: "Analyseur d'URL",
    urlToAnalyze: "URL à analyser",
    urlPlaceholder: "Entrez l'URL complète à analyser...",
    analyzeUrl: "Analyser l'URL",
    urlAnalysisResults: "Résultats de l'analyse",
    protocol: "Protocole",
    hostname: "Nom d'hôte",
    portUrl: "Port",
    pathname: "Chemin",
    queryParams: "Paramètres de requête",
    fragment: "Fragment",
    origin: "Origine",
    isSecure: "Sécurisé",
    hasQuery: "A des paramètres",
    pathSegments: "Segments du chemin",
    invalidUrl: "URL invalide",
    yes: "Oui",
    no: "Non",
    saveUrlResults: "Sauvegarder l'analyse",
    
    // XSS Detector
    xssDetectorTitle: "Détecteur XSS",
    contentToAnalyze: "Contenu à analyser",
    xssContentPlaceholder: "Collez le code HTML/JavaScript à analyser...",
    detectXss: "Détecter les XSS",
    xssAnalysisResults: "Résultats de l'analyse XSS",
    cleanContent: "Contenu sûr",
    riskLevel: "Niveau de risque",
    threatsFound: "Menaces détectées",
    vulnerabilitiesDetected: "Vulnérabilités détectées",
    riskLevelLow: "Faible",
    riskLevelMedium: "Moyen",
    riskLevelHigh: "Élevé",
    threatType: "Type de menace",
    matchedContent: "Contenu détecté",
    position: "Position",
    xssRecommendations: "Recommandations de sécurité",
    contentSafe: "Le contenu semble sûr, mais restez vigilant",
    escapeScriptTags: "Échappez ou supprimez les balises <script>",
    removeEventHandlers: "Supprimez les gestionnaires d'événements inline (onclick, onload, etc.)",
    avoidJsUrls: "Évitez les URLs javascript:",
    validateIframeSources: "Validez les sources des iframes",
    useHtmlEscaping: "Utilisez toujours l'échappement HTML approprié",
    implementCSP: "Implémentez une Content Security Policy (CSP)",
    saveXssResults: "Sauvegarder l'analyse",
    
    // JSON Validator
    jsonValidatorTitle: "Validateur JSON",
    jsonToValidate: "JSON à valider et formater",
    jsonPlaceholder: '{"exemple": "Collez votre JSON ici...", "tableau": [1, 2, 3]}',
    validateJson: "Valider JSON",
    copyFormattedJson: "Copier JSON formaté",
    validationResults: "Résultat de validation",
    jsonValid: "JSON VALIDE",
    jsonInvalid: "JSON INVALIDE",
    jsonStructureAnalysis: "Analyse de la structure",
    jsonType: "Type",
    jsonSize: "Taille",
    jsonDepth: "Profondeur",
    jsonKeys: "Clés",
    errorDetails: "Détails de l'erreur",
    errorLine: "Ligne d'erreur",
    errorSuggestions: "Suggestions de correction",
    checkMissingCommas: "Vérifiez les virgules manquantes ou en trop",
    useDoubleQuotes: "Assurez-vous que les chaînes sont entre guillemets doubles",
    checkMissingBrackets: "Vérifiez les accolades ou crochets manquants",
    stringsNeedQuotes: "Les chaînes doivent être entre guillemets doubles (\")",
    useOnlineValidator: "Utilisez un validateur JSON en ligne pour identifier l'erreur",
    saveJsonResults: "Sauvegarder la validation",

    // Additional terms
    copyResult: "Copier le résultat",
    useToolsBelow: "Utilisez les outils ci-dessous et sauvegardez vos résultats",
    // Loading messages
    loadingPortfolio: "Chargement du portfolio...",
    loadingProjects: "Chargement des projets...",
    loadingTestimonials: "Chargement des témoignages...",
  },
  en: {
    // Navigation
    home: "Home",
    about: "About",
    skills: "Skills",
    projects: "Projects",
    services: "Services",
    contact: "Contact",
    blog: "Blog",
    calculator: "Calculator",
    booking: "Booking", 
    tools: "Tools",
    resources: "Resources",
    
    // Hero Section
    specialist: "Specialist",
    cybersecurity: "Cybersecurity",
    developer: "Developer",
    subtitle: "Digital security expert and Python application development",
    heroDescription: "Digital security expert and Python application development. I help companies in their secure digital transformation.",
    discoverProjects: "Discover my projects",
    myServices: "My services",
    
    // Stats
    projectsCompleted: "Projects completed",
    clientsSatisfied: "Satisfied clients",
    vulnerabilitiesDetected: "Vulnerabilities detected",
    developmentHours: "Development hours",
    
    // Common
    loading: "Loading...",
    readMore: "Read more",
    viewAll: "View all",
    seeMore: "See more",
    requestQuote: "Request quote",
    contactMe: "Contact me",
    learnMore: "Learn more",
    getStarted: "Get started",
    download: "Download",
    preview: "Preview",
    
    // About
    myJourney: "My journey",
    myMission: "My mission",
    workProcess: "My work process",
    personalizedApproach: "Personalized approach",
    technicalExpertise: "Technical expertise",
    concreteResults: "Concrete results",
    reactivity: "Reactivity",
    
    // Skills
    mySkills: "My skills",
    technicalExpertiseSubtitle: "Technical expertise in cybersecurity, Python development and network infrastructure",
    technologiesTools: "Technologies & Tools",
    continuousTraining: "Continuous training",
    skillsNotConfigured: "Skills not configured",
    noSkillsMessage: "Skills for this category have not been added yet.",
    skillsNotAvailable: "Skills not available",
    skillsContactAdmin: "Skills data is not configured yet. Please contact the administrator.",
    technologiesNotConfigured: "Technologies not configured",
    technologiesNotConfiguredMessage: "Technologies and tools are not configured yet.",
    strengthsTitle: "Strengths",
    proactiveSecurity: "Proactive Security",
    proactiveSecurityDesc: "Preventive approach to security with implementation of detection and protection systems against emerging threats.",
    secureCode: "Secure Code",
    secureCodeDesc: "Python application development with security best practices and compliance with industry standards.",
    technicalExcellence: "Technical Excellence",
    technicalExcellenceDesc: "Commitment to excellence with continuous training and constant technological monitoring in cybersecurity.",
    skillsInterest: "Interested in my skills?",
    skillsInterestDesc: "Discover how I can put my expertise at the service of your cybersecurity and Python development projects.",
    viewMyProjects: "View my projects",
    dailyTechWatch: "Daily technological monitoring",
    ctfParticipation: "Participation in CTF (Capture The Flag)",
    onlineTraining: "Specialized online training",
    openSourceContrib: "Contribution to open source projects",
    
    // Projects
    myProjects: "My projects",
    projectsSubtitle: "Discover my technical achievements in cybersecurity, Python and development",
    filterByCategory: "Filter by category",
    filterByLevel: "Filter by level",
    allProjects: "All projects",
    allLevels: "All levels",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    completed: "Completed",
    inProgress: "In progress",
    planned: "Planned",
    keyFeatures: "Key features",
    duration: "Duration",
    
    // Services
    myServicesTitle: "My services",
    servicesSubtitle: "Professional solutions in cybersecurity, Python development and infrastructure",
    collaborationProcess: "My collaboration process",
    whatClientsSay: "What my clients say",
    frequentlyAsked: "Frequently asked questions",
    
    // Contact
    contactTitle: "Contact me",
    contactSubtitle: "Let's discuss your cybersecurity and Python development needs",
    contactInfo: "Contact information",
    socialNetworks: "Social networks",
    quickResponse: "Quick response",
    sendMessage: "Send me a message",
    fullName: "Full name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    serviceOfInterest: "Service of interest",
    selectService: "Select a service",
    sendingMessage: "Sending...",
    sendMessageBtn: "Send message",
    
    // Testimonials
    testimonials: "Testimonials",
    shareExperience: "Share your experience",
    helpOthers: "Help other clients by sharing your testimonial",
    testimonialFormTitle: "Share your experience",
    testimonialFormDesc: "Your testimonial helps us improve our services and inspires other clients",
    company: "Company",
    role: "Role",
    serviceUsed: "Service used",
    rating: "Rating",
    ratingHelper: "Click on stars to rate our service",
    yourTestimonial: "Your testimonial",
    testimonialPlaceholder: "Share your experience with our services...",
    testimonialNote: "Your testimonial will be reviewed before publication. We reserve the right to modify or refuse publication of inappropriate testimonials.",
    testimonialConsent: "By submitting this form, you agree that your testimonial may be published on our website.",
    sendTestimonial: "Send my testimonial",
    sendingTestimonial: "Sending...",
    
    // Blog
    technicalBlog: "Technical Blog",
    blogSubtitle: "Articles and tutorials on cybersecurity and Python development",
    readingTime: "min read",
    publishedOn: "Published on",
    category: "Category",
    tags: "Tags",
    
    // Resources
    resourcesTitle: "Resource Center",
    resourcesSubtitle: "Free guides, tools and resources for cybersecurity",
    downloadResource: "Download",
    downloads: "downloads",
    featured: "Featured",
    freeResources: "Free resources",
    
    // About Page
    aboutMe: "About me",
    aboutMeSubtitle: "Discover my journey and passion for cybersecurity",
    myJourney: "My journey",
    myMission: "My mission",
    workProcess: "My work process",
    personalizedApproach: "Personalized approach",
    technicalExpertise: "Technical expertise",
    concreteResults: "Concrete results",
    reactivity: "Reactivity",
    personalizedApproachDesc: "Each project is unique, I adapt my solutions to your specific needs.",
    technicalExpertiseDesc: "Continuous training in the latest technologies and emerging threats.",
    concreteResultsDesc: "Focus on efficiency and measurable security of your systems.",
    reactivityDesc: "Availability and quick response for your security emergencies.",
    constantTechWatch: "Constant technological monitoring",
    ethicalResponsibleApproach: "Ethical and responsible approach",
    pedagogyTransmission: "Pedagogy and knowledge transfer",
    myMissionDesc: "Democratize cybersecurity and make technologies safe and accessible to all. My goal is to accompany companies in their secure digital transformation, emphasizing prevention and education.",
    someNumbers: "Some numbers",
    readyToCollaborate: "Ready to collaborate?",
    readyToCollaborateDesc: "I am always open to new challenges and collaborations. Let's talk about your cybersecurity and Python development needs.",
    viewMyProjects: "View my projects",
    
    // Contact Page
    contactMe: "Contact me",
    contactSubtitle: "Let's discuss your cybersecurity and Python development needs",
    contactInfo: "Contact information",
    socialNetworks: "Social networks",
    quickResponse: "Quick response",
    sendMessage: "Send me a message",
    fullName: "Full name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    serviceOfInterest: "Service of interest",
    selectService: "Select a service",
    securityAudit: "Security audit",
    pythonDevelopment: "Python development",
    infrastructureSecurity: "Infrastructure security",
    consultingTraining: "Consulting & Training",
    other: "Other",
    phone: "Phone",
    location: "Location",
    availability: "Availability",
    responseWithin24h: "Response within 24h maximum",
    freeQuoteNoCommitment: "Free quote with no commitment",
    freeInitialConsultation: "Free initial consultation",
    technicalSupportIncluded: "Technical support included",
    sendingMessage: "Sending...",
    sendMessageBtn: "Send message",
    messageSentSuccess: "Message sent successfully! I will reply to you quickly.",
    shareExperience: "Share your experience",
    helpOthers: "Help other clients by sharing your testimonial",
    yourName: "Your name",
    yourEmail: "your@email.com",
    subjectOfMessage: "Subject of your message",
    describeProject: "Describe your project or needs...",
    
    // Footer
    followMe: "Follow me",
    backToTop: "Back to top",
    allRightsReserved: "All rights reserved",
    createdWith: "Created with",
    andCoffee: "and lots of coffee",
    navigation: "Navigation",
    services: "Services",
    secureInfrastructure: "Secure infrastructure",
    
    // Error States
    dataNotAvailable: "Data not available",
    contactAdministrator: "Please contact the administrator",
    tryAgainLater: "Please try again later",
    
    // Home page sections
    freeTools: "Free Tools",
    freeToolsDesc: "Use our free online tools for your cybersecurity needs",
    priceCalculator: "Price Calculator",
    priceCalculatorDesc: "Get an instant estimate for your cybersecurity project",
    calculateNow: "Calculate now",
    freeResourcesHome: "Free Resources",
    freeResourcesHomeDesc: "Download our free guides, scripts and templates",
    downloadNow: "Download",
    technicalBlogHome: "Technical Blog",
    technicalBlogHomeDesc: "Discover my articles on cybersecurity and Python",
    readArticles: "Read articles",
    skillsOverview: "Skills Overview",
    skillsOverviewDesc: "An overview of my expertise in cybersecurity and development",
    featuredProjects: "Featured Projects",
    featuredProjectsDesc: "Discover some of my most remarkable projects",
    viewAllProjects: "View all projects",
    whatClientsSay: "What my clients say",
    
    // Footer
    footerDescription: "Cybersecurity specialist and Python developer. I help companies in their secure digital transformation with a modern and efficient approach.",
    skillsTags: ["Cybersecurity", "Python", "Network Security", "Web Development", "IoT", "Cloud Computing", "DevOps", "Pentesting"],
    
    // Dynamic data translations (Skills, Technologies, etc)
    translations: {
      // Skill categories
      'Cybersécurité': 'Cybersecurity',
      'Python': 'Python',
      'Réseaux': 'Networks',
      'Développement Python': 'Python Development',
      'Réseau & Infrastructure': 'Network & Infrastructure',
      
      // Skills  
      'Tests de pénétration': 'Penetration testing',
      'Audit de sécurité': 'Security audit',
      'Sécurisation réseau': 'Network security',
      'Développement Python': 'Python development',
      'Automatisation': 'Automation',
      'Analyse de données': 'Data analysis',
      'Configuration réseau': 'Network configuration',
      'Monitoring': 'Monitoring',
      'Troubleshooting': 'Troubleshooting',
      'Pentesting': 'Pentesting',
      'Forensique': 'Forensics',
      'Conformité RGPD': 'GDPR Compliance',
      'Sécurité des réseaux': 'Network Security',
      'Django/FastAPI': 'Django/FastAPI',
      'APIs REST': 'REST APIs',
      'Tests unitaires': 'Unit Testing',
      'Data Science': 'Data Science',
      'Administration Linux': 'Linux Administration',
      'Firewalls': 'Firewalls',
      'Virtualisation': 'Virtualization',
      'Security Audit': 'Security Audit',
      'Penetration Testing': 'Penetration Testing',
      'Vulnerability Analysis': 'Vulnerability Analysis',
      
      // Project categories and levels
      'Débutant': 'Beginner',
      'Intermédiaire': 'Intermediate',
      'Avancé': 'Advanced',
      'Terminé': 'Completed',
      'En cours': 'In Progress',
      'Planifié': 'Planned',
      
      // Service types
      'Audit de sécurité': 'Security Audit',
      'Tests de pénétration': 'Penetration Testing',
      'Consultation cybersécurité': 'Cybersecurity Consulting',
      'Développement d\'applications': 'Application Development',
      'Scripts d\'automatisation': 'Automation Scripts',
      'Formation': 'Training',
      
      // Blog categories
      'Tutoriel': 'Tutorial',
      'Actualités': 'News',
      'Outils': 'Tools',
      'Conseils': 'Tips',
      
      // Statistics
      'Projets réalisés': 'Projects Completed',
      'Clients satisfaits': 'Satisfied Clients',
      'Vulnérabilités détectées': 'Vulnerabilities Detected',
      'Heures de développement': 'Development Hours',
      'Années d\'expérience': 'Years of Experience',
      'Certifications': 'Certifications',
      'Projets Totaux': 'Total Projects',
      'Taux d\'Achèvement': 'Completion Rate',
      'Articles Publiés': 'Published Articles',
      'Technologies': 'Technologies',
      'Témoignages': 'Testimonials',
      'En Attente': 'Pending',
      'Note Moyenne': 'Average Rating',
      'Téléchargements': 'Downloads',
      'Compétences': 'Skills',
      'Niveau Expert': 'Expert Level',
      'Services': 'Services',
      'Réservations': 'Bookings',
      'Devis Demandés': 'Quotes Requested',
      'Abonnés Newsletter': 'Newsletter Subscribers',
      'Activité (30j)': 'Activity (30d)',
      'Projets Sécurisés': 'Secured Projects',
      'Satisfaction Client': 'Client Satisfaction',
      'Nouvelles certifications': 'New Certifications',
      
      // Services - Titles
      'Audit de Sécurité': 'Security Audit',
      'Développement Python': 'Python Development',
      'Sécurisation d\'Infrastructure': 'Infrastructure Security',
      'Consulting & Formation': 'Consulting & Training',
      
      // Services - Features/Descriptions
      'Analyse complète de votre infrastructure pour identifier les vulnérabilités et risques potentiels.': 'Complete analysis of your infrastructure to identify vulnerabilities and potential risks.',
      'Développement d\'applications Python sécurisées et performantes selon vos besoins.': 'Development of secure and high-performance Python applications according to your needs.',
      'Mise en place et configuration de solutions de sécurité pour votre infrastructure IT.': 'Implementation and configuration of security solutions for your IT infrastructure.',
      'Conseil stratégique et formation de vos équipes en cybersécurité.': 'Strategic consulting and training of your teams in cybersecurity.',
      
      // Services - Features
      'Audit technique complet': 'Complete technical audit',
      'Test de pénétration': 'Penetration testing',
      'Analyse des vulnérabilités': 'Vulnerability analysis',
      'Rapport détaillé': 'Detailed report',
      'Recommandations d\'amélioration': 'Improvement recommendations',
      'Architecture sécurisée': 'Secure architecture',
      'APIs REST performantes': 'High-performance REST APIs',
      'Tests unitaires et intégration': 'Unit and integration tests',
      'Documentation technique': 'Technical documentation',
      'Support et maintenance': 'Support and maintenance',
      'Configuration des firewalls': 'Firewall configuration',
      'Monitoring et alertes': 'Monitoring and alerts',
      'Sauvegarde et récupération': 'Backup and recovery',
      'Politiques de sécurité': 'Security policies',
      'Formation du personnel': 'Staff training',
      'Évaluation des risques': 'Risk assessment',
      'Plan de réponse aux incidents': 'Incident response plan',
      'Certification et conformité': 'Certification and compliance',
      
      // Skills - Individual Skills
      'Audit de sécurité': 'Security audit',
      'Tests de pénétration': 'Penetration testing',
      'Analyse de vulnérabilités': 'Vulnerability analysis',
      'Sécurité réseau': 'Network security',
      'Forensic numérique': 'Digital forensics',
      'Conformité GDPR': 'GDPR compliance',
      'Scripts d\'automatisation': 'Automation scripts',
      'APIs REST': 'REST APIs',
      'Analyse de données': 'Data analysis',
      'Machine Learning': 'Machine Learning',
      'Configuration réseau': 'Network configuration',
      'Administration système': 'System administration',
      'Virtualisation': 'Virtualization',
      'Cloud computing': 'Cloud computing',
      
      // Projects - Categories and Types
      'Scanner de Sécurité': 'Security Scanner',
      'Analyse Forensique': 'Forensic Analysis',
      'Automatisation': 'Automation',
      'Infrastructure': 'Infrastructure',
      'Application Web': 'Web Application',
      'Script Python': 'Python Script',
      'Outil de Monitoring': 'Monitoring Tool',
      
      // Projects - Specific project names and descriptions
      'Vérificateur d\'Intégrité de Fichiers': 'File Integrity Checker',
      'Analyseur de Logs de Sécurité': 'Security Log Analyzer',
      'Scanner de Vulnérabilités Web': 'Web Vulnerability Scanner',
      
      // Project descriptions
      'Outil Python pour surveiller l\'intégrité des fichiers système et détecter les modifications non autorisées.': 'Python tool to monitor system file integrity and detect unauthorized modifications.',
      'Script avancé pour analyser les logs de sécurité et identifier les tentatives d\'intrusion.': 'Advanced script to analyze security logs and identify intrusion attempts.',
      'Application web pour scanner et identifier les vulnérabilités communes dans les applications web.': 'Web application to scan and identify common vulnerabilities in web applications.',
      
      // Project features
      'Calcul de hash MD5/SHA256': 'MD5/SHA256 hash calculation',
      'Surveillance des changements': 'Change monitoring',
      'Base de données d\'empreintes': 'Fingerprint database',
      'Notifications en cas de modification': 'Modification notifications',
      'Interface en ligne de commande': 'Command line interface',
      'Détection d\'anomalies': 'Anomaly detection',
      'Parsing de logs Apache/Nginx': 'Apache/Nginx log parsing',
      'Alertes en temps réel': 'Real-time alerts',
      'Rapports automatisés': 'Automated reports',
      'Dashboard de visualisation': 'Visualization dashboard',
      'Tests OWASP Top 10': 'OWASP Top 10 tests',
      'Interface web moderne': 'Modern web interface',
      'Gestion des utilisateurs': 'User management',
      'Export des résultats': 'Results export',
      'Scan automatisé': 'Automated scanning',
      
      // Project descriptions
      'Outil Python pour surveiller l\'intégrité des fichiers système et détecter les modifications non autorisées.': 'Python tool to monitor system file integrity and detect unauthorized modifications.',
      'Script avancé pour analyser les logs de sécurité et identifier les tentatives d\'intrusion.': 'Advanced script to analyze security logs and identify intrusion attempts.',
      'Application web pour scanner et identifier les vulnérabilités communes dans les applications web.': 'Web application to scan and identify common vulnerabilities in web applications.',
      
      // Project features
      'Calcul de hash MD5/SHA256': 'MD5/SHA256 hash calculation',
      'Surveillance des changements': 'Change monitoring',
      'Base de données d\'empreintes': 'Fingerprint database',
      'Notifications en cas de modification': 'Modification notifications',
      'Interface en ligne de commande': 'Command line interface',
      'Détection d\'anomalies': 'Anomaly detection',
      'Parsing de logs Apache/Nginx': 'Apache/Nginx log parsing',
      'Alertes en temps réel': 'Real-time alerts',
      'Rapports automatisés': 'Automated reports',
      'Dashboard de visualisation': 'Visualization dashboard',
      'Tests OWASP Top 10': 'OWASP Top 10 tests',
      'Interface web moderne': 'Modern web interface',
      'Gestion des utilisateurs': 'User management',
      'Export des résultats': 'Results export',
      'Scan automatisé': 'Automated scanning',
      
      // Process Steps
      'Contact initial': 'Initial contact',
      'Analyse des besoins': 'Needs analysis',
      'Proposition technique': 'Technical proposal',
      'Développement': 'Development',
      'Livraison': 'Delivery',
      
      // Process Steps descriptions
      'Étude détaillée de votre problématique et définition des objectifs.': 'Detailed study of your problem and definition of objectives.',
      'Première prise de contact pour comprendre vos besoins.': 'First contact to understand your needs.',
      'Présentation d\'une solution technique adaptée à vos besoins.': 'Presentation of a technical solution adapted to your needs.',
      'Réalisation de la solution avec des points de contrôle réguliers.': 'Implementation of the solution with regular checkpoints.',
      'Déploiement, formation et suivi de la solution mise en place.': 'Deployment, training and monitoring of the implemented solution.',
      
      // Technologies
      'JavaScript': 'JavaScript',
      'React': 'React',
      'Node.js': 'Node.js',
      'PostgreSQL': 'PostgreSQL',
      'MongoDB': 'MongoDB',
      'Docker': 'Docker',
      'Kubernetes': 'Kubernetes',
      'AWS': 'AWS',
      'Azure': 'Azure',
      'Linux': 'Linux',
      'Windows': 'Windows',
      'Nmap': 'Nmap',
      'Wireshark': 'Wireshark',
      'Metasploit': 'Metasploit',
      'Burp Suite': 'Burp Suite',
      'Git': 'Git',
      'Jenkins': 'Jenkins',
      'Ansible': 'Ansible',
      'Terraform': 'Terraform',
      
      // Additional dynamic translations
      'Forensique': 'Forensics',
      'Planifié': 'Planned'
    },

    // Interactive Tools Page Translations
    interactiveTools: "Interactive Tools",
    interactiveToolsTitle: "Cybersecurity Tools",
    interactiveToolsSubtitle: "Online tool collection for your cybersecurity needs",
    interactiveToolsDesc: "Explore our range of professional cybersecurity tools. Analyze, test, and secure your systems with our specialized utilities developed by experts.",
    freeOnlineTools: "Free online tools",
    chooseToolBelow: "Choose a tool below to start your analysis",
    
    // Tool Interface Labels
    analysisResults: "Analysis results",
    securityScore: "Security score",
    suggestedImprovements: "Suggested improvements",
    analysisResult: "Analysis result",
    scanResults: "Scan results",
    validationResults: "Validation results",
    xssAnalysisResults: "XSS analysis results",
    
    // Common Tool Actions
    enterText: "Enter text",
    enterPassword: "Enter password",
    enterUrl: "Enter URL",
    enterHost: "Enter host",
    enterJson: "Enter JSON",
    enterCode: "Enter code",
    
    // Tool Specific Labels - Password Analyzer
    passwordAnalyzerTitle: "Password Analyzer",
    passwordToAnalyze: "Password to analyze",
    passwordPlaceholder: "Enter a password...",
    excellentPassword: "Excellent password!",
    entropy: "Entropy",
    
    // Tool Specific Labels - Port Scanner
    portScannerTitle: "Port Scanner",
    portScannerSimulation: "Port Scanner (Simulation)",
    targetHostLabel: "Target IP address or hostname",
    targetHostPlaceholder: "192.168.1.1 or example.com",
    startScan: "Start scan",
    scanInProgress: "Scan in progress",
    portsScanned: "ports scanned",
    educationalSimulation: "⚠️ This is an educational simulation. In practice, only scan your own systems or with authorization.",
    
    // Tool Specific Labels - Cipher Tool
    cipherToolTitle: "Cipher Tool",
    cipherToolAES: "AES Cipher/Decipher Tool",
    textToCipher: "Text to encrypt",
    cipherText: "Encrypted text",
    encryptionKey: "Encryption key",
    secretKey: "Secret key...",
    enterMessage: "Enter your message...",
    enterCipherText: "Enter encrypted text...",
    result: "Result",
    
    // Tool Specific Labels - URL Analyzer  
    urlAnalyzerTitle: "URL Analyzer",
    urlToAnalyze: "URL to analyze",
    urlPlaceholder: "https://example.com/path?param=value",
    urlAnalysisTitle: "URL Analysis",
    protocol: "Protocol",
    hostname: "Hostname",
    port: "Port",
    path: "Path",
    queryParams: "Query parameters",
    pathSegments: "Path segments",
    origin: "Origin",
    secured: "✓ Secured",
    
    // Tool Specific Labels - XSS Detector
    xssDetectorTitle: "XSS Detector",
    xssAnalysisReport: "XSS Analysis Report",
    codeToAnalyze: "HTML/JavaScript code to analyze",
    xssCodePlaceholder: "Paste your HTML or JavaScript code here...",
    analyzeXssThreats: "Analyze XSS threats",
    highRisk: "HIGH RISK",
    mediumRisk: "MEDIUM RISK", 
    secured: "SECURED",
    threatsDetected: "Threats detected",
    vulnerabilities: "vulnerabilities",
    detectedVulnerabilities: "Detected vulnerabilities",
    recommendations: "Recommendations",
    position: "Position",
    xssEducationalNote: "ℹ️ This tool detects potential XSS patterns in HTML/JavaScript code for educational purposes.",
    
    // Tool Specific Labels - JSON Validator
    jsonValidatorTitle: "JSON Validator",
    jsonToValidate: "JSON to validate and format",
    jsonPlaceholder: '{"example": "Paste your JSON here...", "array": [1, 2, 3]}',
    validateJson: "Validate JSON",
    copyFormattedJson: "Copy formatted JSON",
    jsonValid: "VALID JSON",
    jsonInvalid: "INVALID JSON",
    jsonStructureAnalysis: "Structure analysis",
    // Password feedback messages
    atLeast8Chars: "At least 8 characters",
    lowercaseLetters: "Lowercase letters", 
    uppercaseLetters: "Uppercase letters",
    numbers: "Numbers",
    specialChars: "Special characters",
    avoidRepetitions: "Avoid repetitions",
    excellentPassword: "Excellent password!",
    
    // Password strength levels
    passwordStrengthWeak: "Weak",
    passwordStrengthMedium: "Medium",
    passwordStrengthStrong: "Strong", 
    passwordStrengthVeryStrong: "Very Strong",
    
    // Cipher error messages
    errorIncorrectKey: "Error: Incorrect key or invalid text",
    errorCipherOperation: "Error during encryption/decryption",
    
    // URL analysis error
    invalidUrl: "Invalid URL",
    
    // XSS security recommendations
    escapeScriptTags: "Escape or remove <script> tags",
    removeEventHandlers: "Remove inline event handlers (onclick, onload, etc.)",
    avoidJsUrls: "Avoid javascript: URLs",
    validateIframeSources: "Validate iframe sources",
    useHtmlEscaping: "Always use proper HTML escaping",
    implementCSP: "Implement a Content Security Policy (CSP)",
    contentSafe: "Content appears safe, but stay vigilant",
    
    // JSON error suggestions
    checkMissingCommas: "Check for missing or extra commas",
    useDoubleQuotes: "Make sure strings are in double quotes",
    checkMissingBrackets: "Check for missing brackets or braces", 
    stringsNeedQuotes: "Strings must be in double quotes (\")",
    useOnlineValidator: "Use an online JSON validator to identify the error",
    
    // Tool Names
    hashGenerator: "Hash Generator",
    passwordAnalyzer: "Password Analyzer",
    portScanner: "Port Scanner",
    cipherTool: "Cipher/Decipher Tool",
    urlAnalyzer: "URL Analyzer",
    xssDetector: "XSS Detector",
    jsonValidator: "JSON Validator",
    
    // Tool Descriptions
    hashGeneratorDesc: "Generate MD5, SHA1, SHA256 hashes",
    passwordAnalyzerDesc: "Check password strength",
    portScannerDesc: "Port scanning simulation",
    cipherToolDesc: "AES encryption/decryption",
    urlAnalyzerDesc: "Analyze URL structure",
    xssDetectorDesc: "Detect potential XSS vulnerabilities",
    jsonValidatorDesc: "Validate and format JSON",
    
    // Results History
    resultsHistory: "Results History",
    showHistory: "Show History",
    hideHistory: "Hide History",
    savedResults: "saved results",
    noSavedResults: "No saved results",
    exportResults: "Export Results",
    clearAllResults: "Clear All Results",
    deleteResult: "Delete This Result",
    
    // Common Tool Actions
    generate: "Generate",
    analyze: "Analyze",
    scan: "Scan",
    encrypt: "Encrypt",
    decrypt: "Decrypt",
    validate: "Validate",
    detect: "Detect",
    copy: "Copy",
    copied: "Copied!",
    save: "Save",
    saved: "Saved!",
    clear: "Clear",
    reset: "Reset",
    
    // Hash Generator
    hashGeneratorTitle: "Hash Generator",
    enterTextToHash: "Text to hash",
    enterTextPlaceholder: "Enter text to hash...",
    generateHashes: "Generate Hashes",
    hashResults: "Hash Results",
    copyHash: "Copy Hash",
    saveHashResults: "Save Results",
    
    // Password Analyzer
    passwordAnalyzerTitle: "Password Analyzer",
    enterPassword: "Password to analyze",
    passwordPlaceholder: "Enter password to analyze...",
    passwordStrength: "Password Strength",
    securityScore: "Security Score",
    entropy: "Entropy",
    recommendations: "Recommendations",
    passwordStrengthWeak: "Weak",
    passwordStrengthMedium: "Medium",
    passwordStrengthStrong: "Strong",
    passwordStrengthVeryStrong: "Very Strong",
    atLeast8Chars: "At least 8 characters",
    lowercaseLetters: "Lowercase letters",
    uppercaseLetters: "Uppercase letters",
    numbers: "Numbers",
    specialChars: "Special characters",
    avoidRepetitions: "Avoid repetitions",
    savePasswordResults: "Save Analysis",
    
    // Port Scanner
    portScannerTitle: "Port Scanner",
    targetHost: "Target Host",
    targetHostPlaceholder: "Enter IP address or hostname...",
    startScan: "Start Scan",
    scanInProgress: "Scan in Progress",
    scanResults: "Scan Results",
    port: "Port",
    status: "Status",
    service: "Service",
    openPorts: "Open Ports",
    closedPorts: "Closed Ports",
    saveScanResults: "Save Scan",
    
    // Cipher Tool
    cipherToolTitle: "Cipher/Decipher Tool",
    textToCipher: "Text to encrypt/decrypt",
    cipherTextPlaceholder: "Enter text to encrypt or decrypt...",
    encryptionKey: "Encryption Key",
    keyPlaceholder: "Enter encryption key...",
    mode: "Mode",
    encryptMode: "Encrypt",
    decryptMode: "Decrypt",
    performOperation: "Perform Operation",
    cipherResult: "Result",
    errorIncorrectKey: "Error: Incorrect key or invalid text",
    errorCipherOperation: "Error during encryption/decryption",
    saveCipherResults: "Save Result",
    
    // URL Analyzer
    urlAnalyzerTitle: "URL Analyzer",
    urlToAnalyze: "URL to analyze",
    urlPlaceholder: "Enter complete URL to analyze...",
    analyzeUrl: "Analyze URL",
    urlAnalysisResults: "Analysis Results",
    protocol: "Protocol",
    hostname: "Hostname",
    portUrl: "Port",
    pathname: "Path",
    queryParams: "Query Parameters",
    fragment: "Fragment",
    origin: "Origin",
    isSecure: "Secure",
    hasQuery: "Has Parameters",
    pathSegments: "Path Segments",
    invalidUrl: "Invalid URL",
    yes: "Yes",
    no: "No",
    saveUrlResults: "Save Analysis",
    
    // XSS Detector
    xssDetectorTitle: "XSS Detector",
    contentToAnalyze: "Content to analyze",
    xssContentPlaceholder: "Paste HTML/JavaScript code to analyze...",
    detectXss: "Detect XSS",
    xssAnalysisResults: "XSS Analysis Results",
    cleanContent: "Safe Content",
    riskLevel: "Risk Level",
    threatsFound: "Threats Found",
    vulnerabilitiesDetected: "Vulnerabilities Detected",
    riskLevelLow: "Low",
    riskLevelMedium: "Medium",
    riskLevelHigh: "High",
    threatType: "Threat Type",
    matchedContent: "Detected Content",
    position: "Position",
    xssRecommendations: "Security Recommendations",
    contentSafe: "Content appears safe, but stay vigilant",
    escapeScriptTags: "Escape or remove <script> tags",
    removeEventHandlers: "Remove inline event handlers (onclick, onload, etc.)",
    avoidJsUrls: "Avoid javascript: URLs",
    validateIframeSources: "Validate iframe sources",
    useHtmlEscaping: "Always use proper HTML escaping",
    implementCSP: "Implement Content Security Policy (CSP)",
    saveXssResults: "Save Analysis",
    
    // JSON Validator
    jsonValidatorTitle: "JSON Validator",
    jsonToValidate: "JSON to validate and format",
    jsonPlaceholder: '{"example": "Paste your JSON here...", "array": [1, 2, 3]}',
    validateJson: "Validate JSON",
    copyFormattedJson: "Copy Formatted JSON",
    validationResults: "Validation Result",
    jsonValid: "VALID JSON",
    jsonInvalid: "INVALID JSON",
    jsonStructureAnalysis: "Structure Analysis",
    jsonType: "Type",
    jsonSize: "Size",
    jsonDepth: "Depth",
    jsonKeys: "Keys",
    errorDetails: "Error Details",
    errorLine: "Error Line",
    errorSuggestions: "Correction Suggestions",
    checkMissingCommas: "Check for missing or extra commas",
    useDoubleQuotes: "Make sure strings are in double quotes",
    checkMissingBrackets: "Check for missing braces or brackets",
    stringsNeedQuotes: "Strings must be in double quotes (\")",
    useOnlineValidator: "Use an online JSON validator to identify the error",
    saveJsonResults: "Save Validation",

    // Additional terms
    copyResult: "Copy result",
    useToolsBelow: "Use the tools below and save your results",
    // Loading messages
    loadingPortfolio: "Loading portfolio...",
    loadingProjects: "Loading projects...",
    loadingTestimonials: "Loading testimonials...",
    
    language: "en"
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'fr' ? 'en' : 'fr');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const td = (dynamicText) => {
    // Translate dynamic data (from APIs)
    return translations[language].translations?.[dynamicText] || dynamicText;
  };

  const value = {
    language,
    toggleLanguage,
    t,
    td,
    isFrench: language === 'fr'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};